### ISSUE TITLE
Is there any way to get postmarketOS on ME173X with Android 4.2.2?

### ISSUE THREAD

**Issue by k1dehner** [me176c-dev/me176c-boot#16]
I have an ASUS MeMO Pad HD7 (ME173X) with Android 4.2.2 installed.
I would like to install postmarket OS on the device. Is there any way to get postmarket OS directly onto an Android 4.2.2 MeMO Pad? Or do I have to upgrade to Android 5 first?
How can I do that? Can I just take the ME176C firmware (Kitkat to Lollipop) and put it on the ME173X device? 
Unfortunately, I have not yet succeeded in unlocking the bootloader using the standard procedure and putting the device into bootloader mode.
Would be very happy if you could suggest a solution.

**Comment by stephan-gh** [comment]
The ME173X seems to have a Mediatek processor, which is completely different from the Intel processor in the ME176C. Unfortunately, this means you cannot reuse anything from this project. I'm afraid I also don't have any suggestions how to unlock the bootloader, since this will also be Mediatek-specific. Perhaps there are others who are (or have been) working on devices with the same Mediatek processor? I hope you can get it working. :)
